using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Sic.CountryInfos.SourceGenerator.Generation;

internal class LanguageEnumBuilder
{
    private readonly Func<CultureInfo, string> _getLanguage;
    private readonly Func<CultureInfo, string> _getDocumentation;
    private readonly StringBuilder _enumBuilder;
    private readonly SortedList<string, CultureInfo> _cultures;

    public LanguageEnumBuilder(
        string documentation,
        string namespaceName,
        string fileName,
        Func<CultureInfo, string> getLanguage,
        Func<CultureInfo, string> getDocumentation)
    {
        _getLanguage = getLanguage;
        _getDocumentation = getDocumentation;
        _cultures = new();
        _enumBuilder = new StringBuilder();
        _enumBuilder.AppendLine($@"{Constants.AutoGeneratedComment}
namespace {namespaceName}.Enums;
{documentation}
public enum {fileName}
{{");
    }

    public void AddLocaleCode(CultureInfo culture)
    {
        _cultures.Add(culture.Name, culture);
    }


    public string Build()
    {
        var languages = _cultures.Values
            .Select(c => (EnumName: _getLanguage(c), Culture: c))
            // as cultures can have the same language name, we need do Distinct by
            .GroupBy(t => t.EnumName)
            .Select(g => g.OrderBy(g => g.Culture.LCID).First())
            .Select((t) => (t.EnumName, t.Culture));


        foreach (var (enumName, culture) in languages)
        {
            _enumBuilder.AppendLine($@"    /// <summary>
    /// {_getDocumentation(culture)}
    /// </summary>
    {enumName} = {culture.LCID},");
        }

        _enumBuilder.Append("}");
        return _enumBuilder.ToString();
    }
}